name: Deploy to Screeps

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        npm install -g screeps-deploy
    
    - name: Build TypeScript
      run: |
        npm run build
        if [ ! -d "./dist" ]; then
          echo "Error: dist directory not found after build."
          exit 1
        fi
        echo "Contents of dist directory:"
        ls -la dist/
    
    - name: Deploy to Screeps
      env:
        SCREEPS_TOKEN: ${{ secrets.SCREEPS_TOKEN }}
      run: |
        echo "=== Installing Dependencies ==="
        sudo apt-get update
        sudo apt-get install -y jq
        
        echo "=== Environment Information ==="
        echo "Current working directory: $(pwd)"
        echo "GitHub workspace: ${{ github.workspace }}"
        
        echo -e "\n=== Dist Directory Details ==="
        DIST_PATH="${{ github.workspace }}/dist"
        echo "Using dist path: $DIST_PATH"
        
        echo -e "\n=== Preparing Code for Deployment ==="
        # Создаем временный файл с кодом
        cd $DIST_PATH
        CODE_FILES=$(find . -name "*.js" -not -name "*.d.ts" -not -name "*.js.map")
        echo "Found files:"
        echo "$CODE_FILES"
        
        # Создаем JSON с кодом
        CODE_JSON="{"
        for file in $CODE_FILES; do
          filename=$(basename "$file" .js)
          content=$(cat "$file" | jq -Rs .)
          CODE_JSON="$CODE_JSON\"$filename\":$content,"
        done
        CODE_JSON="${CODE_JSON%,}}"
        
        echo -e "\n=== Deploying to Screeps ==="
        echo "Sending code to Screeps..."
        curl -X POST \
          -H "X-Token: $SCREEPS_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"branch\":\"main\",\"modules\":$CODE_JSON}" \
          https://screeps.com/api/user/code
        
        echo -e "\n=== Deployment Complete ==="
      working-directory: ${{ github.workspace }} 