name: Deploy to Screeps

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        npm install -g screeps-deploy
    
    - name: Build TypeScript
      run: |
        npm run build
        ls -la dist/
    
    - name: Deploy to Screeps
      env:
        SCREEPS_TOKEN: ${{ secrets.SCREEPS_TOKEN }}
        SCREEPSDEPLOY_CONFIG_PATH: ${{ github.workspace }}/screeps-deploy.config.js
      run: |
        echo "Using config at: $SCREEPSDEPLOY_CONFIG_PATH"
        cat $SCREEPSDEPLOY_CONFIG_PATH
        screeps-deploy --server main --path ./dist 