name: Deploy to Screeps

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        npm install -g screeps-deploy
    
    - name: Build TypeScript
      run: |
        npm run build
        if [ ! -d "./dist" ]; then
          echo "Error: dist directory not found after build."
          exit 1
        fi
        echo "Contents of dist directory:"
        ls -la dist/
    
    - name: Deploy to Screeps
      env:
        SCREEPS_TOKEN: ${{ secrets.SCREEPS_TOKEN }}
      run: |
        echo "=== Environment Information ==="
        echo "Current working directory: $(pwd)"
        echo "GitHub workspace: ${{ github.workspace }}"
        
        echo -e "\n=== Directory Structure ==="
        echo "Root directory contents:"
        ls -la ${{ github.workspace }}
        
        echo -e "\n=== Dist Directory Details ==="
        DIST_PATH="${{ github.workspace }}/dist"
        echo "Using dist path: $DIST_PATH"
        echo "Dist directory exists: [ -d $DIST_PATH ] && echo 'Yes' || echo 'No'"
        echo "Dist directory permissions:"
        ls -la $DIST_PATH
        
        echo -e "\n=== Creating Config File ==="
        CONFIG_DIR="/opt/hostedtoolcache/node/18.20.8/x64/lib/node_modules/screeps-deploy"
        echo "module.exports = { servers: { main: { host: 'screeps.com', port: 443, secure: true, token: '$SCREEPS_TOKEN', branch: 'main', path: '$DIST_PATH' } } };" > $CONFIG_DIR/config.js
        echo "Config file created at: $CONFIG_DIR/config.js"
        cat $CONFIG_DIR/config.js
        
        echo -e "\n=== Starting Deployment ==="
        echo "Running screeps-deploy with path: $DIST_PATH"
        export SCREEPSDEPLOY_CONFIG_PATH="$CONFIG_DIR/config.js"
        echo "Using config path: $SCREEPSDEPLOY_CONFIG_PATH"
        screeps-deploy --server main --path "$DIST_PATH" --token "$SCREEPS_TOKEN" --branch main --verbose
      working-directory: ${{ github.workspace }} 