name: Generate Architecture Documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.js'
      - '**/*.ts'

  pull_request:
    branches: [ main ]
    paths:
      - '**/*.js'
      - '**/*.ts'

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm install
        if [ $? -ne 0 ]; then
          echo "Failed to install dependencies"
          exit 1
        fi
    
    - name: Generate documentation
      run: |
        echo "Generating documentation..."
        npm run generate
        if [ $? -ne 0 ]; then
          echo "Failed to generate documentation"
          exit 1
        fi
    
    - name: Commit and push documentation
      run: |
        echo "Committing documentation changes..."
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add architecture.md
        git commit -m "docs: update architecture documentation [skip ci]" || true
        git push origin main || true 